#!/bin/bash

# Hide "last login" line when starting a new terminal session
touch $HOME/.hushlogin

# Install zsh
echo 'Install oh-my-zsh'
echo '-----------------'
sudo apt-get install zsh -y
rm -rf $HOME/.oh-my-zsh
curl -L https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh

# Add global gitignore
ln -s $HOME/.dotfiles/shell-linux/.global-gitignore $HOME/.global-gitignore
git config --global core.excludesfile $HOME/.global-gitignore

# Symlink zsh prefs
rm $HOME/.zshrc
ln -s $HOME/.dotfiles/shell-linux/.zshrc $HOME/.zshrc

# Symlink dircolors prefs
rm $HOME/.dircolors
ln -s $HOME/.dotfiles/shell-linux/.dircolors $HOME/.dircolors

# Symlink vim prefs
rm $HOME/.vimrc
ln -s $HOME/.dotfiles/shell-linux/.vimrc $HOME/.vimrc
rm $HOME/.vim
ln -s $HOME/.dotfiles/shell-linux/.vim $HOME/.vim

# Symlink yarn prefs
rm $HOME/.yarnrc
ln -s $HOME/.dotfiles/shell-linux/.yarnrc $HOME/.yarnrc

# Activate z
cd ~/.dotfiles/shell-linux
chmod +x z.sh

# Set new shell
chsh -s /usr/bin/zsh

echo 'Apt-get update'
echo '----------------'
sudo apt-get update && sudo apt-get upgrade && sudo apt-get dist-upgrade

echo 'Install node'
echo '-----------'
curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
sudo apt-get install nodejs -y

echo 'Install pkg-config'
echo '------------------'
sudo apt-get install pkg-config -y

echo 'Install wget'
echo '------------'
sudo apt-get install wget -y

echo 'Install httpie'
echo '--------------'
sudo apt-get install httpie -y

echo 'Install ncdu'
echo '------------'
sudo apt-get install ncdu -y

echo 'Install ack'
echo '-----------'
sudo apt-get install ack -y

echo 'Install vim'
echo '-----------'
sudo apt-get install vim -y

echo 'Install apache'
echo '-----------'
sudo apt-get install apache2 -y

echo 'Install php'
echo '-----------'
sudo apt-get install php -y
sudo apt-get install php-pear php-fpm php-dev php-zip php-curl php-xmlrpc php-gd php-mysql php-mbstring php-xml libapache2-mod-php -y

echo 'Install composer'
echo '----------------'
cd ~/.dotfiles
EXPECTED_SIGNATURE="$(wget -q -O - https://composer.github.io/installer.sig)"
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
ACTUAL_SIGNATURE="$(php -r "echo hash_file('sha384', 'composer-setup.php');")"

if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]
then
    echo 'ERROR: Invalid Composer installer signature'
    rm composer-setup.php
else
    php composer-setup.php --quiet
    rm composer-setup.php
    echo 'move composer to /usr/local/bin/composer'
    sudo mv -f composer.phar /usr/local/bin/composer
fi

echo 'Update pecl'
echo '-------------------'
sudo pecl channel-update pecl.php.net

echo 'Install imagemagick'
echo '-------------------'
sudo apt-get install imagemagick -y

echo 'Install imagick'
echo '---------------'
sudo pecl install imagick

echo 'Install memcached'
echo '-----------------'
sudo pecl install memcached

echo 'Install xdebug'
echo '--------------'
sudo pecl install xdebug

echo 'Install redis'
echo '-------------'
sudo pecl install redis

echo 'Install php-cs-fixer'
echo '--------------------'
composer global require friendsofphp/php-cs-fixer

echo 'Install laravel envoy'
echo '---------------------'
composer global require "laravel/envoy=~1.0"

echo 'Install phpunit-watcher'
echo '-----------------------'
composer global require spatie/phpunit-watcher

echo 'Install mixed-content-scanner-cli'
echo '---------------------------------'
composer global require spatie/mixed-content-scanner-cli

echo 'Install yarn'
echo '------------'
sudo apt-get install yarn -y


echo '++++++++++++++++++++++++++++++'
echo '++++++++++++++++++++++++++++++'
echo 'All done!'
echo 'Things to do to make the oxide terminal theme work:'
echo '1. Install hack font included in ~/.dotfiles/misc'

echo '++++++++++++++++++++++++++++++'
echo 'Some optional tidbits'

echo '1. Make a .dotfiles-custom/shell-linux/.aliases for your personal commands'

echo '++++++++++++++++++++++++++++++'
echo '++++++++++++++++++++++++++++++'
